apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eso-sys-deny-all-traffic
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: external-secrets-operator
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress