apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eso-sys-allow-api-server-egress-for-main-controller
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: external-secrets-operator
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  policyTypes:
    - Egress
    - Ingress
  egress:
    - ports:
        - protocol: TCP
          port: 6443
  ingress:
    # Allow Prometheus/monitoring to scrape metrics
    - from:
      - namespaceSelector:
          matchLabels:
            name: openshift-user-workload-monitoring
      ports:
        - protocol: TCP
          port: 8080