---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - clusterissuers
  - issuers
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - clusterexternalsecrets
  - clusterpushsecrets
  - clustersecretstores
  - externalsecrets
  - pushsecrets
  - secretstores
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - clusterexternalsecrets/finalizers
  - clusterexternalsecrets/status
  - clusterpushsecrets/finalizers
  - clusterpushsecrets/status
  - clustersecretstores/finalizers
  - clustersecretstores/status
  - externalsecrets/finalizers
  - externalsecrets/status
  - pushsecrets/finalizers
  - pushsecrets/status
  - secretstores/finalizers
  - secretstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - generators.external-secrets.io
  resources:
  - acraccesstokens
  - cloudsmithaccesstokens
  - clustergenerators
  - ecrauthorizationtokens
  - fakes
  - gcraccesstokens
  - generatorstates
  - githubaccesstokens
  - grafanas
  - mfas
  - passwords
  - quayaccesstokens
  - sshkeys
  - stssessiontokens
  - uuids
  - vaultdynamicsecrets
  - webhooks
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - externalsecretsconfigs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - externalsecretsconfigs/finalizers
  - externalsecretsmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - externalsecretsconfigs/status
  verbs:
  - get
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - externalsecretsmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - externalsecretsmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
