---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-sdk-server
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: bitwarden-sdk-server
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.6.0"
    app.kubernetes.io/managed-by: external-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitwarden-sdk-server
      app.kubernetes.io/instance: external-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitwarden-sdk-server
        app.kubernetes.io/instance: external-secrets
    spec:
      serviceAccountName: bitwarden-sdk-server
      securityContext: {}
      containers:
        - name: bitwarden-sdk-server
          securityContext: {}
          image: "ghcr.io/external-secrets/bitwarden-sdk-server:v0.6.0"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /certs
              name: bitwarden-tls-certs
          ports:
            - name: http
              containerPort: 9998
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: http
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /ready
              port: http
              scheme: HTTPS
          resources: {}
      volumes:
        - name: bitwarden-tls-certs
          secret:
            secretName: bitwarden-tls-certs
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem
              - key: ca.crt
                path: ca.pem
