---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitwarden-sdk-server
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: bitwarden-sdk-server
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.5.3"
    app.kubernetes.io/managed-by: external-secrets-operator
